# Conexion a PostgreSQL - apunta a reserva_hoteles (se crea automaticamente)
spring.datasource.url=jdbc:postgresql://localhost:5432/reserva_hoteles
spring.datasource.username=postgres
spring.datasource.password=Camael

# JPA / Hibernate - none porque las tablas las crea DatabaseInitializer
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Desactivar scripts SQL (lo hace DatabaseInitializer)
spring.sql.init.mode=never

# Evitar referencias circulares en JSON
spring.jackson.serialization.fail-on-empty-beans=false

# Puerto del servidor
server.port=8080
